name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - master

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev


    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'ap-southeast-1'  

    - name: 'Deploy Wordpress to EC2'
      'run: |
        scp -i ${{cloudcrafters_pem}} -r local/app* ubuntu@52.221.183.103:/var/www/html/
        ssh -i ${{cloudcrafters_pem}} ubuntu@52.221.183.103 'sudo systemctl restart apache2'
    
    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v1
    
    
    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Format'
      run: terraform fmt -check

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan







